/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ShopByShapesRouteImport } from './routes/shop-by-shapes'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ProductSlipDressRouteImport } from './routes/product.slip-dress'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopByShapesRoute = ShopByShapesRouteImport.update({
  id: '/shop-by-shapes',
  path: '/shop-by-shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlipDressRoute = ProductSlipDressRouteImport.update({
  id: '/product/slip-dress',
  path: '/product/slip-dress',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/admin/subscribers',
    path: '/admin/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/landing': typeof LandingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop-by-shapes': typeof ShopByShapesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/product/$handle': typeof ProductHandleRoute
  '/product/slip-dress': typeof ProductSlipDressRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/landing': typeof LandingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop-by-shapes': typeof ShopByShapesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/product/$handle': typeof ProductHandleRoute
  '/product/slip-dress': typeof ProductSlipDressRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/landing': typeof LandingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop-by-shapes': typeof ShopByShapesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/product/$handle': typeof ProductHandleRoute
  '/product/slip-dress': typeof ProductSlipDressRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/collections'
    | '/landing'
    | '/privacy-policy'
    | '/shipping-returns'
    | '/shop-by-shapes'
    | '/terms-of-service'
    | '/product/$handle'
    | '/product/slip-dress'
    | '/admin/subscribers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collections'
    | '/landing'
    | '/privacy-policy'
    | '/shipping-returns'
    | '/shop-by-shapes'
    | '/terms-of-service'
    | '/product/$handle'
    | '/product/slip-dress'
    | '/admin/subscribers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/collections'
    | '/landing'
    | '/privacy-policy'
    | '/shipping-returns'
    | '/shop-by-shapes'
    | '/terms-of-service'
    | '/product/$handle'
    | '/product/slip-dress'
    | '/_authenticated/admin/subscribers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CollectionsRoute: typeof CollectionsRoute
  LandingRoute: typeof LandingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopByShapesRoute: typeof ShopByShapesRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProductSlipDressRoute: typeof ProductSlipDressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-by-shapes': {
      id: '/shop-by-shapes'
      path: '/shop-by-shapes'
      fullPath: '/shop-by-shapes'
      preLoaderRoute: typeof ShopByShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/slip-dress': {
      id: '/product/slip-dress'
      path: '/product/slip-dress'
      fullPath: '/product/slip-dress'
      preLoaderRoute: typeof ProductSlipDressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CollectionsRoute: CollectionsRoute,
  LandingRoute: LandingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopByShapesRoute: ShopByShapesRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProductSlipDressRoute: ProductSlipDressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
